name: tpk_app
description: "Aplikasi TPK dengan SQLite"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  pdf: ^3.10.4
  printing: ^5.12.0
  share_plus: ^7.2.1
  excel: ^2.1.0
  path_provider: ^2.1.2
  intl: any
  open_file: ^3.5.10
  syncfusion_flutter_pdf: ^31.1.20
  image_picker: ^1.2.0
  image: ^4.1.3
  shared_preferences: ^2.5.3
  sqflite: ^2.3.0
  path: ^1.8.3
  blue_thermal_printer: ^1.2.3
  permission_handler: ^12.0.1
  # esc_pos_printer_plus: ^2.0.4
  # esc_pos_utils_plus: ^2.0.3
  network_info_plus: ^5.0.0
  crypto: ^3.0.3
  device_info_plus: ^9.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_profile.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
